In [3]:
#Q3. Singular Value Decomposition (SVD): 
#Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print 
#matrices U, Σ, and 𝑉 .Verify that A equals the product of U, Σ, and 𝑉.Additionally, find the rank 2 
#and rank 3 approximations of matrix A. 

In [6]:
import numpy as np
# Define the matrix A obtained from Question 2
matrix_A = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 0],
                     [1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 0],
                     [1, 2, 3, 4, 5]])
print("Matrix A:")
print(matrix_A)
# Perform Singular Value Decomposition (SVD)
U, Sigma, Vt = np.linalg.svd(matrix_A)

# Separate the singular values into a diagonal matrix
Sigma_matrix = np.diag(Sigma)

# Compute the rank 2 and rank 3 approximations of matrix A
rank2approximation = U[:, :2] @ Sigma_matrix[:2, :2] @ Vt[:2, :]
rank3approximation = U[:, :3] @ Sigma_matrix[:3, :3] @ Vt[:3, :]

print("\nRank 2 Approximation of Matrix A:")
print(rank2approximation)
print("\nRank 3 Approximation of Matrix A:")
print(rank3approximation)

Matrix A:
[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]]

Rank 2 Approximation of Matrix A:
[[ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00
   5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00  8.00000000e+00  9.00000000e+00
  -6.21960987e-17]
 [ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00
   5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00  8.00000000e+00  9.00000000e+00
   7.77214796e-16]
 [ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00
   5.00000000e+00]]

Rank 3 Approximation of Matrix A:
[[ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00
   5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00  8.00000000e+00  9.00000000e+00
  -7.94858585e-17]
 [ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00
   5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00  8.00000000e+00  9.00000000e+00
   7.94504555e-16]
 [ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00
   5.00000000e+00]]
