In [1]:
#Q2. Row Echelon Form: 
#Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the 
#random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its 
#Row Echelon Form by performing elementary row operations. 

In [1]:
import numpy as np
# Set the random seed based on the last two digits of your roll number
roll_number = 57 # Change this to your actual last two digits
np.random.seed(roll_number)
# Create a random 5x5 matrix A with entries between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))
print("Random Matrix A:")
print(A)

# Perform elementary row operations to reduce A to its Row Echelon Form
rows, cols = A.shape
lead = 0
row = 0

while lead < cols and row < rows:
    # Find the first non-zero entry in the current column below the pivot
    if A[row, lead] == 0:
        non_zero_row = row + 1
        while non_zero_row < rows and A[non_zero_row, lead] == 0:
            non_zero_row += 1
        if non_zero_row == rows:
            lead += 1
            row = 0
            continue
        else:
            A[[row, non_zero_row]] = A[[non_zero_row, row]]

    # Scale the pivot row to make the pivot value 1
    A[row] = A[row] / A[row, lead]

    # Eliminate non-zero entries below the pivot
    for i in range(rows):
        if i != row:
            factor = A[i, lead]
            A[i] = A[i] - factor * A[row]

    lead += 1
    row += 1

print("\nRow Echelon Form of Matrix A:")
print(A)

Random Matrix A:
[[6 5 6 8 2]
 [8 8 1 7 9]
 [5 8 8 1 1]
 [2 0 1 6 4]
 [5 9 6 2 8]]

Row Echelon Form of Matrix A:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
